// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV0tpnnw6NPaFdbwH9z_ciCB8b0sDG3fc',
    appId: '1:143989401243:web:21ea24b2070124f793c83e',
    messagingSenderId: '143989401243',
    projectId: 'character-ai-delta',
    authDomain: 'character-ai-delta.firebaseapp.com',
    storageBucket: 'character-ai-delta.firebasestorage.app',
    measurementId: 'G-18ZSHR8W1D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC01cZIMh2Tv3k_xw4KzYGOGlDSRc0ZvQw',
    appId: '1:143989401243:android:bea6d2d0a9d9f70b93c83e',
    messagingSenderId: '143989401243',
    projectId: 'character-ai-delta',
    storageBucket: 'character-ai-delta.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaGMaoVQc-_JM79B4MhL3XM7OgBNMIsDU',
    appId: '1:143989401243:ios:e7af1a3e230c37ea93c83e',
    messagingSenderId: '143989401243',
    projectId: 'character-ai-delta',
    storageBucket: 'character-ai-delta.firebasestorage.app',
    iosBundleId: 'com.example.characterAiDelta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaGMaoVQc-_JM79B4MhL3XM7OgBNMIsDU',
    appId: '1:143989401243:ios:e7af1a3e230c37ea93c83e',
    messagingSenderId: '143989401243',
    projectId: 'character-ai-delta',
    storageBucket: 'character-ai-delta.firebasestorage.app',
    iosBundleId: 'com.example.characterAiDelta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDV0tpnnw6NPaFdbwH9z_ciCB8b0sDG3fc',
    appId: '1:143989401243:web:312c35853259a2f593c83e',
    messagingSenderId: '143989401243',
    projectId: 'character-ai-delta',
    authDomain: 'character-ai-delta.firebaseapp.com',
    storageBucket: 'character-ai-delta.firebasestorage.app',
    measurementId: 'G-CBDN1KLBRN',
  );

}