// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAupalWZvj8xvCj3hVX9xhm9oW9i4Zy4EM',
    appId: '1:601471141084:web:5e0502bf4e8f3f75692019',
    messagingSenderId: '601471141084',
    projectId: 'characterai-gamma',
    authDomain: 'characterai-gamma.firebaseapp.com',
    storageBucket: 'characterai-gamma.firebasestorage.app',
    measurementId: 'G-HSVJTTS9V3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOpIyswZgsvnBqXALw8Xq8ivXI-sENkUo',
    appId: '1:601471141084:android:031f48e68831ee5a692019',
    messagingSenderId: '601471141084',
    projectId: 'characterai-gamma',
    storageBucket: 'characterai-gamma.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKk5uuEAl70ijsr-lPV-2j7f5kyyImnjg',
    appId: '1:601471141084:ios:304ca23d8f0bfba7692019',
    messagingSenderId: '601471141084',
    projectId: 'characterai-gamma',
    storageBucket: 'characterai-gamma.firebasestorage.app',
    iosBundleId: 'app.character.roleplay.ai.friend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKk5uuEAl70ijsr-lPV-2j7f5kyyImnjg',
    appId: '1:601471141084:ios:1ad941db715e21f2692019',
    messagingSenderId: '601471141084',
    projectId: 'characterai-gamma',
    storageBucket: 'characterai-gamma.firebasestorage.app',
    iosBundleId: 'com.example.characterAiGamma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAupalWZvj8xvCj3hVX9xhm9oW9i4Zy4EM',
    appId: '1:601471141084:web:dfea3e6e39591595692019',
    messagingSenderId: '601471141084',
    projectId: 'characterai-gamma',
    authDomain: 'characterai-gamma.firebaseapp.com',
    storageBucket: 'characterai-gamma.firebasestorage.app',
    measurementId: 'G-SRZK43579E',
  );

}